const COLORS = {
  BLACK: '#000',
  GREY01: '#ccc',
  GREY02: '#777',
  NEAR_BLACK: '#170901',
  NEUTRAL: '#eeeadc',
  PRIMARY: '#d44102',
  SECONDARY: '#1cc8d7',
  WHITE: '#fff',
};

const COPY = {
  SWITCH_TO_DARK: 'Switch to dark mode',
  SWITCH_TO_LIGHT: 'Switch to light mode',
};

export const MODE = {
  DARK: 'dark',
  LIGHT: 'light',
};

const DARK = Object.freeze({
  BACKGROUND: {
    BODY: COLORS.BLACK,
    HEADER: COLORS.BLACK,
    FOOTER: COLORS.BLACK,
  },
  BORDER: {
    HEADER: COLORS.BLACK,
  },
  BUTTON: {
    BODY: {
      BACKGROUND: COLORS.WHITE,
      TEXT: COLORS.BLACK,
      OUTLINE: COLORS.PRIMARY,
    },
    HEADER: {
      BACKGROUND: COLORS.WHITE,
      TEXT: COLORS.BLACK,
      OUTLINE: COLORS.WHITE,
    },
  },
  COPY: {
    TOGGLE_BUTTON: COPY.SWITCH_TO_LIGHT,
  },
  IMG: {
    BOX_SHADOW: COLORS.BLACK,
  },
  LINK: {
    BODY: { TEXT: COLORS.WHITE, UNDERLINE: COLORS.PRIMARY },
    HEADER: { TEXT: COLORS.WHITE, UNDERLINE: COLORS.WHITE },
  },
  MODE: MODE.DARK,
  SHADOW: {
    HEADER: COLORS.WHITE,
  },
  TAG: {
    BACKGROUND: COLORS.GREY01,
    BORDER: COLORS.NEAR_BLACK,
    COLOR: COLORS.NEAR_BLACK,
  },
  TEXT: {
    BODY: COLORS.WHITE,
    HEADER: COLORS.WHITE,
    LOGO: COLORS.PRIMARY,
  },
});

const LIGHT = Object.freeze({
  BACKGROUND: {
    BODY: COLORS.WHITE,
    HEADER: COLORS.WHITE,
    FOOTER: COLORS.WHITE,
  },
  BORDER: {
    HEADER: COLORS.NEUTRAL,
  },
  BUTTON: {
    BODY: {
      BACKGROUND: COLORS.SECONDARY,
      TEXT: COLORS.WHITE,
      OUTLINE: COLORS.SECONDARY,
    },
    HEADER: {
      BACKGROUND: COLORS.BLACK,
      TEXT: COLORS.NEUTRAL,
      OUTLINE: COLORS.BLACK,
    },
  },
  COPY: {
    TOGGLE_BUTTON: COPY.SWITCH_TO_DARK,
  },
  IMG: {
    BOX_SHADOW: COLORS.GREY02,
  },
  LINK: {
    BODY: { TEXT: COLORS.BLACK, UNDERLINE: COLORS.PRIMARY },
    HEADER: { TEXT: COLORS.BLACK, UNDERLINE: COLORS.BLACK },
  },
  MODE: MODE.LIGHT,
  TAG: {
    BACKGROUND: COLORS.GREY01,
    BORDER: COLORS.NEAR_BLACK,
    COLOR: COLORS.NEAR_BLACK,
  },
  TEXT: {
    BODY: COLORS.BLACK,
    HEADER: COLORS.BLACK,
    LOGO: COLORS.PRIMARY,
  },
  SHADOW: {
    HEADER: COLORS.WHITE,
  },
});

export const THEME = {
  DARK,
  LIGHT,
};
